const Map<String, String> barbershopFallbacks = {
  'nav_booking': 'Citas',
  'nav_reservations': 'Citas',
  'nav_home': 'Inicio',
  'nav_profile': 'Perfil',
  'home_hello': 'Hola',
  'home_good_morning': 'Buenos días',
  'home_search_hint': 'Buscar servicios, barberos...',
  'home_search_results': 'Resultados de servicios',
  'filter_results_title': 'Servicios filtrados',
  'home_categories': 'Tipos de servicio',
  'home_popular': 'Servicios destacados',
  'home_nearby': 'Servicios cercanos',
  'home_view_all': 'Ver todo',
  'home_featured_title': 'Servicios destacados',
  'home_premium_title': 'Experiencias premium',
  'home_business_hours_title': 'Horario de atención',
  'home_business_hours_hint': 'Sujeto a cambios en días feriados',
  'home_policy_title': 'Política de cancelación',
  'home_policy_text':
      'Podés cancelar o reprogramar hasta 4 horas antes de tu cita.',
  'home_location_title': 'Ubicación y contacto',
  'home_location_text': 'Puntarenas, El Roble, Costa Rica',
  'home_brand_badge': 'Premium Experience',
  'home_hero_title': 'Barbería Tres Amigos',
  'home_hero_subtitle': 'Cortes, barba y experiencias premium',
  'home_hours_card_title': 'Horario semanal',
  'home_hours_card_body':
      'Lun 10:00 AM - 7:00 PM · Mar 10:00 AM - 12:00 PM · 2:00 PM - 8:00 PM · Vie-Sáb 10:00 AM - 7:00 PM · Domingo cerrado',
  'home_location_card_body': 'Puntarenas, El Roble, Costa Rica',
  'home_contact_card_body': '+506 8888-3366 · hola@barberiatresamigos.com',
  'home_staff_title': 'Barberos destacados',
  'home_staff_card_title': 'Administrar barberos y asignaciones',
  'home_staff_card_body':
      'Creá, editá, activá y asigná barberos desde un solo lugar.',
  'home_premium_badge': 'Premium',
  'home_service_barbers': 'Barberos',
  'home_distance_sample': 'Puntarenas',

  'booking_details_title': 'Detalle de la cita',
  'booking_detail_ground_label': 'Servicio',
  'booking_detail_code': 'Código de cita',
  'booking_detail_barber': 'Barbero',
  'booking_detail_price': 'Precio',
  'booking_detail_duration': 'Duración',
  'booking_detail_description': 'Descripción',
  'booking_barber_title': 'Barbero',
  'booking_barber_optional': 'Sin barbero seleccionado',
  'booking_barber_selected': 'Barbero seleccionado',
  'booking_barber_choose': 'Elegir barbero',
  'booking_barber_picker_title': 'Elegí tu barbero',
  'booking_barber_picker_hint': 'Elegí un barbero o continuá sin asignar uno.',
  'booking_barber_picker_error': 'No se pudieron cargar los barberos',
  'booking_barber_none': 'Sin preferencia de barbero',
  'booking_barber_none_subtitle': 'Continuar sin asignar un barbero',
  'booking_barber_none_available':
      'No hay barberos disponibles para este servicio',
  'booking_barber_label': 'Barbero',
  'booking_barber_unassigned': 'Sin asignar',
  'booking_proceed_payment': 'Continuar al pago',
  'select_date_time_title': 'Elegí tu horario',
  'select_no_slots': 'No hay horarios disponibles',
  'select_choose_slot': 'Elegí un horario disponible',
  'select_time': 'Seleccioná el horario',
  'select_duration_1h': '1 h',
  'select_duration_2h': '2 h',

  'grounds_add_title': 'Agregar servicio',
  'grounds_operating_hours': 'Horario del local',
  'grounds_duration_label': 'Duración del servicio',
  'grounds_my_title': 'Mis servicios',
  'grounds_empty': 'Todavía no hay servicios',
  'grounds_category_title': 'Tipo de servicio',
  'grounds_created_appbar': 'Servicios creados',
  'grounds_created_title': 'Servicio creado',
  'grounds_created_subtitle':
      'Tu servicio se creó correctamente y ya aparece en Mis servicios.',
  'grounds_back_to_list': 'Volver a Mis servicios',
  'grounds_create_failed': 'No se pudo crear el servicio',
  'grounds_edit_details': 'Editar servicio',
  'grounds_opens': 'Abre',
  'grounds_closes': 'Cierra',
  'grounds_duration_one': '1 hora',
  'grounds_duration_two': '2 horas',
  'grounds_duration_three': '3 horas',
  'grounds_status': 'Estado',
  'grounds_active': 'Activo',
  'grounds_inactive': 'Inactivo',
  'grounds_edit': 'Editar',
  'grounds_activate': 'Activar',
  'grounds_deactivate': 'Desactivar',
  'grounds_status_updated': 'Estado actualizado',
  'grounds_update_failed': 'No se pudo actualizar',
  'grounds_name_required': 'El nombre y la dirección son obligatorios',
  'grounds_hour': 'hora',
  'grounds_add_photos_title': 'Agregar fotos',
  'grounds_take_new_photo': 'Tomar nueva foto',
  'grounds_from_album': 'Desde la galería',
  'grounds_admin_only':
      'Solo los administradores pueden acceder a esta sección',

  'profile_title': 'Perfil',
  'profile_my_profile': 'Mi perfil',
  'profile_change_password': 'Cambiar contraseña',
  'profile_settings': 'Configuración',
  'profile_privacy': 'Política de privacidad',
  'profile_help': 'Ayuda',
  'profile_about': 'Sobre nosotros',
  'profile_rate_us': 'Calificarnos',
  'profile_my_grounds': 'Mis servicios',
  'profile_logout': 'Cerrar sesión',
  'profile_logout_confirm': '¿Seguro que querés cerrar sesión?',
  'profile_language_label': 'Idioma',

  'login_title': 'Iniciá sesión',
  'login_subtitle': 'Tu estilo, tu experiencia',
  'login_email': 'Correo electrónico',
  'login_password': 'Contraseña',
  'login_forgot': '¿Olvidaste tu contraseña?',
  'login_button': 'Iniciar sesión',
  'login_skip': 'Saltar',
  'login_or_continue': 'o continuar con',
  'login_continue_google': 'Google',
  'login_continue_facebook': 'Facebook',
  'login_continue_apple': 'Apple',
  'login_signup_prompt': '¿No tenés cuenta? Registrate',

  'signup_title': 'Crear cuenta',
  'signup_subtitle': 'Completá tus datos para empezar a reservar citas.',
  'signup_button': 'Registrarme',
  'signup_have_account': '¿Ya tenés cuenta? Iniciá sesión',
  'signup_confirm_password': 'Confirmar contraseña',
  'signup_complete_fields': 'Completá todos los campos',
  'signup_failed': 'No se pudo crear la cuenta',

  'onboarding_tagline': 'CORTES, BARBA Y EXPERIENCIAS PREMIUM',
  'onboarding_get_started': 'COMENZAR',
  'onboarding_skip': 'OMITIR',

  'booking_success_title': 'Cita confirmada',
  'booking_success_subtitle': 'Tu cita quedó registrada correctamente.',
  'booking_rebook_success_title': 'Cita reprogramada',
  'booking_rebook_success_subtitle':
      'Tu cita fue reprogramada. Podés cancelar o reprogramar hasta 4 horas antes.',
  'booking_cancel_limit':
      'No se puede cancelar dentro de las 4 horas previas al inicio.',
  'booking_cancel_title': 'Cancelar cita',
  'booking_cancel_confirm': '¿Seguro que querés cancelar esta cita?',
  'booking_cancel_confirm_action': 'Sí, cancelar',
  'booking_cancelled': 'Cita cancelada',
  'booking_cancel_failed': 'No se pudo cancelar',
  'booking_rebook_cta': 'Reprogramar',
  'booking_cancel_cta': 'Cancelar',
  'booking_rebook_progress': 'Reprogramando...',
  'booking_cancel_progress': 'Cancelando...',
  'booking_rebook_failed': 'No se pudo reprogramar',

  'btn_continue': 'Continuar',
  'btn_save': 'Guardar',
  'btn_saving': 'Guardando...',
  'btn_cancel': 'Cancelar',
  'btn_no': 'No',
  'btn_back_home': 'Volver al inicio',
  'btn_add': 'Agregar',
  'btn_confirm': 'Confirmar',

  'staff_load_failed': 'No se pudieron cargar los barberos',
  'staff_empty': 'No hay barberos',
  'staff_title': 'Barbero',
  'staff_services': 'servicios',
  'add_staff': 'Agregar barbero',
  'edit': 'Editar',
  'assign': 'Asignar',
  'manage_staff': 'Administrar barberos',
  'admin_only': 'Solo los administradores pueden acceder a esta sección',
  'payment_title': 'Pago',
  'payment_method_card': 'Tarjeta',
  'payment_method_cash': 'Efectivo',
  'payment_add_card': 'Agregar nueva tarjeta',
  'payment_processing': 'Procesando...',
  'payment_login_required': 'Iniciá sesión para completar la cita',

  'common_facilities': 'Servicios del local',
  'facility_parking': 'Parqueo',
  'facility_camera': 'Seguridad',
  'facility_waiting': 'Sala de espera',
  'facility_changing': 'Área de preparación',
  'ground_rating_sample': '4.9 (212 reseñas)',
  'ground_price_sample': 'CRC 6 000',
  'ground_description_placeholder':
      'Reservá este servicio eligiendo un horario disponible.',
  'ground_list_title': 'Servicios disponibles',
  'ground_main_label': 'Opción principal',
  'ground_login_required': 'Iniciá sesión para continuar',
  'ground_book_now': 'Reservar cita',
  'ground_service_duration': 'Duración',
};
