const Map<String, String> barbershopFallbacks = {
  'nav_booking': 'Appointments',
  'nav_reservations': 'Appointments',
  'home_search_hint': 'Search services',
  'home_search_results': 'Services results',
  'filter_results_title': 'Filtered services',
  'home_categories': 'Service types',
  'home_popular': 'Popular services',
  'home_nearby': 'Nearby services',
  'booking_details_title': 'Appointment details',
  'booking_detail_ground_label': 'Service',
  'booking_detail_code': 'Appointment code',
  'booking_detail_barber': 'Barber',
  'booking_barber_title': 'Barber',
  'booking_barber_optional': 'No barber selected',
  'booking_barber_selected': 'Barber selected',
  'booking_barber_choose': 'Choose barber',
  'booking_barber_picker_title': 'Select barber',
  'booking_barber_picker_hint': 'Choose a barber or continue without one.',
  'booking_barber_picker_error': 'Failed to load barbers',
  'booking_barber_none': 'No barber preference',
  'booking_barber_none_subtitle': 'Continue without assigning a barber',
  'booking_barber_none_available': 'No barbers available for this service',
  'booking_barber_label': 'Barber',
  'booking_barber_unassigned': 'Unassigned',
  'booking_proceed_payment': 'Continue to payment',
  'select_date_time_title': 'Select appointment time',
  'select_no_slots': 'No available appointment slots',
  'select_choose_slot': 'Please choose an available appointment slot',
  'grounds_add_title': 'Add service',
  'grounds_operating_hours': 'Shop hours',
  'grounds_duration_label': 'Duration per appointment',
  'grounds_my_title': 'My services',
  'grounds_empty': 'No services yet',
  'grounds_category_title': 'Service type',
  'grounds_created_appbar': 'Services created',
  'grounds_created_title': 'Service created',
  'grounds_created_subtitle':
      'Your service has been created successfully and is now listed under My services.',
  'grounds_back_to_list': 'Back to My services',
  'grounds_create_failed': 'Failed to create service',
  'admin_reservations_title': 'Appointments today',
  'admin_reservations_empty': 'No appointments for this day',
  'profile_my_grounds': 'My services',
};
